// Patientenpfad – Daten und Konfiguration
//
// Felder: nr, phase, titel, akteur[], objekt[], op, dr[], domäne, gesetze[], standards[], struktur, detail, ist, luecke, forderungen
// struktur: 'strukturiert' | 'teilstrukturiert' | 'unstrukturiert'  — Ist-Zustand des erzeugten Datenobjekts
// ist:       Was heute vorhanden ist (Ist-Zustand des Prozessschritts)
// luecke:    Was fehlt (Lücke zwischen Ist und Soll)
// forderungen: Was die AG fordert
// phase:  'vor' | 'im' | 'nach'
// op:     E = Erzeugt, V = Verändert, G = Gelöscht
// Exportiert: 2026-05-18

// ── Konfiguration (pflegbar über den Editor) ──────────────────────────────────

const meta = {
  domaenen: [
    "Anamnese",
    "Befunde",
    "Behandlung",
    "Diagnosen",
    "Dokumente",
    "Einwilligung",
    "Kommunikation",
    "Medikation",
    "Nachsorge",
    "Patient",
    "Pflege",
    "Termin",
    "Überweisung",
    "Verlauf"
  ],

  akteure: [
    "Angehörige",
    "Arzt",
    "Niedergelassener Arzt",
    "Patient",
    "Pflege",
    "Sozialdienst",
    "Verwaltung"
  ],

  datenobjekte: [
    "AHB / Reha-Antrag",
    "Abschlussdokumentation / Fallabschluss",
    "Anamnese",
    "Arztbrief / Entlassbericht",
    "Check-in Bestätigung",
    "Diagnose / Befunddokumentation",
    "Einwilligungserklärung",
    "Entlassungsplan",
    "Laborwerte / Befunde im Portal",
    "Medikationsplan",
    "Nachricht / Rückfrage",
    "Nachsorgetermin",
    "Patientenfall / Fallakte",
    "Patientenstammdaten",
    "Pflegeassessment",
    "Pflegedokumentation / Vitalwerte",
    "Pflegerischer Überleitungsbogen",
    "Pflegeüberleitungsdokument",
    "Strukturierte Datenobjekte in der ePA",
    "Terminanfrage / Terminbestätigung",
    "Überweisung / Einweisung",
    "Untersuchungsergebnisse / Befunde",
    "Verlaufsdokumentation / PROMs",
    "Vorbefunde / Fremdbefunde",
    "Widerspruch"
  ],

  standards: [
    "ABDA Medikationsliste",
    "DICOM",
    "DIN EN ISO/IEEE 11073 Point of Care",
    "HL7 - FHIR Consent",
    "HL7 CDA R2",
    "HL7 FHIR R4 (Appointment)",
    "HL7 FHIR R4 (CarePlan)",
    "HL7 FHIR R4 (Communication)",
    "HL7 FHIR R4 (Condition)",
    "HL7 FHIR R4 (Consent)",
    "HL7 FHIR R4 (DiagnosticReport)",
    "HL7 FHIR R4 (DocumentReference)",
    "HL7 FHIR R4 (Encounter)",
    "HL7 FHIR R4 (EpisodeOfCare)",
    "HL7 FHIR R4 (MedicationStatement)",
    "HL7 FHIR R4 (Observation)",
    "HL7 FHIR R4 (QuestionnaireResponse)",
    "HL7 FHIR R4 (ServiceRequest)",
    "HL7 v2",
    "ICD-10-GM",
    "IHE MHD",
    "IHE PIX/PDQ",
    "IHE RAD",
    "IHE XDS.b",
    "ISIK 6 - Formular",
    "ISiK Basismodul",
    "ISiK Terminplanung",
    "KBV FHIR-Basisprofile",
    "KBV Medikationsplan",
    "KIM (Kommunikation im Medizinwesen)",
    "LOINC",
    "OPS",
    "SNOMED CT",
    "gematik TI-Messenger",
    "gematik VSDM",
    "gematik ePA-Spezifikation"
  ],

  rechtsgrundlagen: [
    "AMVV § 14",
    "BGB § 630a (Behandlungsvertrag)",
    "BGB § 630d (Einwilligung)",
    "BGB § 630f (Dokumentationspflicht)",
    "BGB § 630f + § 630g",
    "BGB § 630g (Akteneinsicht)",
    "DiGAV",
    "DSGVO Art. 6",
    "DSGVO Art. 6 Abs. 1",
    "DSGVO Art. 6 + Art. 9",
    "DSGVO Art. 7 + Art. 9",
    "DSGVO Art. 9",
    "KHEntgG",
    "KHEntgG § 2",
    "KHZG",
    "KrPflG",
    "MBO-Ä § 10",
    "PatDatSchG",
    "SGB IX",
    "SGB V § 31a (Medikationsplan)",
    "SGB V § 39",
    "SGB V § 39 (Entlassmanagement)",
    "SGB V § 40 (Anschlussheilbehandlung)",
    "SGB V § 68a (DiGA)",
    "SGB V § 73 (Überweisungen)",
    "SGB V § 75 (Terminvermittlung)",
    "SGB V § 75a",
    "SGB V § 291 (eGK)",
    "SGB V § 301",
    "SGB V § 341 ff. (ePA)",
    "SGB V § 341–360 (ePA)",
    "SGB V § 342 (ePA-Einwilligung)",
    "SGB XI",
    "SGB XI § 14 (Pflegebedürftigkeit)",
    "SGB XI § 37",
    "StGB § 203 (Schweigepflicht)",
    "TKG"
  ]
};

// ── Prozessschritte ───────────────────────────────────────────────────────────

const data = [

  // ── Vor dem Krankenhaus ──────────────────────────────────────────────────────

  {
    nr: 1,
    phase: "vor",
    titel: "Termin anfragen / buchen",
    akteur: ["Angehörige", "Patient", "Verwaltung"],
    objekt: ["Terminanfrage / Terminbestätigung"],
    op: "E",
    dr: ["portal", "versorgung"],
    domäne: "Termin",
    gesetze: ["DSGVO Art. 6 Abs. 1", "SGB V § 75 (Terminvermittlung)"],
    standards: ["HL7 FHIR R4 (Appointment)", "ISiK Terminplanung"],
    struktur: "unstrukturiert",
    detail: "Terminvereinbarung für ambulante Vorstellung oder stationäre Aufnahme. Das Portal ist die primäre Schnittstelle – der Patient löst den Prozess aus.",
    ist: "Krankenhausportale bieten heute Terminbuchungsfunktionen an — teils als eigenständige Lösungen, teils über den Terminservicedienst der KVen. Mit ISiK Terminplanung und HL7 FHIR Appointment existieren Standards für die strukturierte Abbildung von Terminen. Die Integration zwischen Portal und KIS ist in vielen Häusern bereits umgesetzt.",
    luecke: "Der Patient ist beim Termin noch nicht eindeutig identifiziert — eine Verknüpfung mit bestehenden Stammdaten oder der ePA ist zu diesem Zeitpunkt nicht möglich. Die FHIR-Integration zwischen Portal und KIS ist nicht durchgängig umgesetzt. Die beim Termin erfassten Informationen (Grund, Vorgeschichte) werden nicht strukturiert in den weiteren Prozess überführt.",
    forderungen: "Eindeutige Patientenidentifikation bereits bei der Terminbuchung etablieren.\nTerminbuchung als Startpunkt des Datenprozesses verstehen: erfasste Informationen strukturiert in den weiteren Patientenpfad überführen.\nDurchgängige FHIR-Integration zwischen Portal und KIS als Mindeststandard definieren (ISiK Terminplanung)."
  },
  {
    nr: 2,
    phase: "vor",
    titel: "Überweisung / Einweisung bereitstellen",
    akteur: ["Niedergelassener Arzt", "Patient"],
    objekt: ["Überweisung / Einweisung"],
    op: "E",
    dr: ["versorgung", "epa"],
    domäne: "Überweisung",
    gesetze: ["SGB V § 73 (Überweisungen)", "DSGVO Art. 9"],
    standards: ["HL7 FHIR R4 (ServiceRequest)", "KBV FHIR-Basisprofile", "HL7 CDA R2"],
    struktur: "unstrukturiert",
    detail: "Die Überweisung wird im Kontext des Krankenhauses erstmalig bereitgestellt. Heute oft noch als Papier oder PDF – ein klassischer Medienbruch.",
    ist: "Die Überweisung und Einweisung existieren heute überwiegend als Papier oder PDF — ein klassischer Medienbruch. Mit der eÜberweisung (KBV) ist ein erster elektronischer Standard im Aufbau. HL7 FHIR ServiceRequest und KBV FHIR-Basisprofile bieten eine strukturierte Grundlage für die Abbildung.",
    luecke: "Die elektronische Überweisung ist noch nicht flächendeckend eingeführt — der Medienbruch (Papier, Fax, PDF) ist der Regelfall. Die Einweisung löst keinen automatischen Zugriff auf die ePA aus. Die enthaltenen strukturierten Informationen (Diagnose, Fragestellung) erreichen das Krankenhaus nicht maschinenlesbar und müssen manuell ins KIS übertragen werden.",
    forderungen: "Elektronische Überweisung und Einweisung flächendeckend einführen — strukturiert, maschinenlesbar, auf Basis von FHIR ServiceRequest.\nEinweisung als Auslöser für den frühzeitigen ePA-Zugriff nutzen.\nPatientenidentifikation bereits mit der Einweisung verknüpfen, um Medienbrüche im weiteren Prozess zu vermeiden."
  },
  {
    nr: 3,
    phase: "vor",
    titel: "Stammdaten erfassen / aktualisieren",
    akteur: ["Patient", "Verwaltung"],
    objekt: ["Patientenstammdaten"],
    op: "E, V",
    dr: ["portal", "versorgung"],
    domäne: "Patient",
    gesetze: ["DSGVO Art. 6 + Art. 9", "SGB V § 291 (eGK)", "KHEntgG § 2"],
    standards: ["HL7 FHIR R4 (Patient)", "IHE PIX/PDQ", "gematik VSDM", "ISiK Basismodul"],
    struktur: "strukturiert",
    detail: "Kontaktdaten und Versicherungsdaten werden erfasst oder aktualisiert. Datenobjekt kann sowohl neu entstehen als auch verändert werden.",
    ist: "Mit dem VSDM existiert eine funktionierende Infrastruktur für Versichertenstammdaten — Meldeadresse und Versicherungsstatus sind über die Gesundheitskarte abrufbar. Die Erfassung am Aufnahmeschalter ist in deutschen Krankenhäusern etabliert. ISiK Basismodul und IHE PIX/PDQ bieten Standards für die strukturierte Patientenidentifikation.",
    luecke: "Angaben am Aufnahmeschalter stimmen häufig nicht mit den Daten auf der Gesundheitskarte überein — eine automatische Aktualisierung des Stammsatzes findet nicht statt. Für die Kommunikation über Patientenportale relevante Felder fehlen im VSDM: E-Mail, Telefon, abweichende Anschrift sowie Hausarzt inkl. dessen KIM-Adresse. Patient wird an mehreren Stellen neu erfasst, statt auf einen gemeinsamen Datensatz zuzugreifen.",
    forderungen: "VSDM als Grundlage nutzen und um portalrelevante Felder erweitern (E-Mail, Telefon, Hausarzt inkl. KIM-Adresse).\nEinmalige Stammdatenerfassung als Prozessziel: Daten werden einmal erhoben und sektorenübergreifend genutzt — nicht mehrfach neu eingegeben.\nEinheitlichen Standard für Patientenidentifikation in Portal, KIS und ePA definieren (Grundlage: ISiK Basismodul, IHE PIX/PDQ)."
  },
  {
    nr: 4,
    phase: "vor",
    titel: "Vorbefunde bereitstellen",
    akteur: ["Niedergelassener Arzt", "Patient"],
    objekt: ["Vorbefunde / Fremdbefunde"],
    op: "E",
    dr: ["portal", "versorgung", "epa"],
    domäne: "Befunde",
    gesetze: ["BGB § 630g (Akteneinsicht)", "DSGVO Art. 9", "SGB V § 341 ff. (ePA)"],
    standards: ["HL7 FHIR R4 (DocumentReference)", "IHE MHD", "IHE XDS.b", "gematik ePA-Spezifikation"],
    struktur: "unstrukturiert",
    detail: "Upload oder Zugriff auf vorhandene Dokumente. Idealerweise strukturierte Datenobjekte – nicht PDFs.",
    ist: "Mit dem VSDM ist die ePA ab dem ersten institutionellen Kontakt (Versichertenkarte einlesen) grundsätzlich zugänglich — eine bereits funktionierende Infrastruktur. Patientenportale bieten Upload-Funktionen für Dokumente. Patienten bringen Befunde per Papier oder elektronisch mit. Mit der Klinischen Dokumentenliste (KDL) existiert ein Kategorisierungsstandard für Dokumente in der ePA.\nLink: https://simplifier.net/guide/kdl-implementierungsleitfaden-2025?version=current",
    luecke: "Zugriff auf die ePA ist erst ab dem ersten institutionellen Kontakt möglich — nicht bereits bei Einweisung oder Überweisung. PoPP (Proof of Patient Presence) könnte im Kontext von Patientenportalen einen früheren Zugriff ermöglichen, ist aber noch nicht etabliert. Bereitgestellte Dokumente liegen überwiegend unstrukturiert vor (PDF) — strukturierte Informationen zu Medikamenten, Labor etc. fehlen. Die Klinische Dokumentenliste (KDL) ist vorhanden, wird aber nicht durchgängig genutzt.",
    forderungen: "Frühzeitiger Zugriff auf die ePA — bereits ab Einweisung oder Überweisung, nicht erst ab erstem institutionellem Kontakt.\nZugriff über das Patientenportal ermöglichen, verknüpft mit Einweisung oder Überweisung.\nStrukturierte Zusendung von Vorbefunden durch Vorbehandler (Standard: LOINC, KDL).\nKrankenhaussysteme müssen bereitgestellte strukturierte Informationen automatisch verarbeiten können.\nKI-gestützte Aufbereitung bereitgestellter Vorbefunde als mittelfristiges Ziel definieren."
  },
  {
    nr: 5,
    phase: "vor",
    titel: "Anamnesebogen ausfüllen",
    akteur: ["Angehörige", "Patient", "Pflege", "Sozialdienst"],
    objekt: ["Anamnese"],
    op: "E",
    dr: ["portal", "versorgung", "epa"],
    domäne: "Anamnese",
    gesetze: ["BGB § 630a (Behandlungsvertrag)", "DSGVO Art. 9"],
    standards: ["HL7 CDA R2", "HL7 FHIR R4 (QuestionnaireResponse)", "ISIK 6 - Formular"],
    struktur: "unstrukturiert",
    detail: "Digitale medizinische Vorgeschichte. Zentrales Datenobjekt – wird im gesamten Pfad weitergenutzt. Sollte strukturiert vorliegen, nicht als Freitext.",
    ist: "ISiK Stufe 6 führt mit dem Formular-Modul einen neuen Standard für digitale Anamnese ein, der gezielt auf diesen Anwendungsfall zugeschnitten ist. HL7 FHIR QuestionnaireResponse ist ein reifer internationaler Standard. In der Praxis findet die Anamnese heute überwiegend in der medizinischen Aufnahme statt — digital in KIS-Systemen oder auf Papier.\nLink: https://gemspec.gematik.de/ig/fhir/isik/formular/6.0.0-rc/index.html",
    luecke: "Der Anamneseprozess beginnt an jeder Sektorgrenze neu: Patientinnen und Patienten geben dieselben Informationen beim Hausarzt, beim Facharzt und im Krankenhaus wiederholt an. Das Datenobjekt \"Anamnese\" wird nicht weitergereicht und verfeinert, sondern bei jedem Akteur neu erzeugt. Der Prozess ist fragmentiert — nicht das Werkzeug fehlt, sondern die Prozesskontinuität.",
    forderungen: "Die Anamnese als kontinuierlichen, akteursübergreifenden Prozess gestalten: einmal erheben, sektorenübergreifend verfeinern und ergänzen — nicht neu erzeugen.\nEinheitlichen Standard als technische Grundlage festlegen (ISiK Formular, FHIR QuestionnaireResponse), der diesen Prozess trägt.\nAnamnesedaten in KIS, ePA und Patientenportalen abrufbar und erweiterbar machen."
  },
  {
    nr: 6,
    phase: "vor",
    titel: "Einwilligungen erteilen",
    akteur: ["Patient"],
    objekt: ["Einwilligungserklärung", "Widerspruch"],
    op: "E",
    dr: ["portal", "versorgung", "epa", "ehds"],
    domäne: "Einwilligung",
    gesetze: ["BGB § 630d (Einwilligung)", "DSGVO Art. 7 + Art. 9", "SGB V § 342 (ePA-Einwilligung)"],
    standards: ["HL7 FHIR R4 (Consent)", "gematik ePA-Spezifikation"],
    struktur: "unstrukturiert",
    detail: "Datenschutz und Behandlungseinwilligung. Einwilligung und Widerspruch sind eigenständige Datenobjekte mit unterschiedlicher rechtlicher Wirkung.",
    ist: "Der Widerspruch gegen Zugriff und Befüllung der ePA ist gesetzlich vorgesehen (SGB V § 342), wurde in der Umsetzung jedoch an die Krankenhaussysteme (KIS) delegiert — mit heterogenen, nicht standardisierten Lösungen als Ergebnis. HL7 FHIR Consent ist ein reifer Standard für die strukturierte Abbildung von Einwilligungen, wird aber nicht durchgängig eingesetzt. Aufklärungsprozesse in Krankenhäusern existieren, teils digital unterstützt, aber ohne einheitliche Grundlage.\nLink: https://simplifier.net/guide/einwilligungsmanagement?version=current",
    luecke: "Ein einrichtungsübergreifendes, standardisiertes Consent-Management fehlt. Die Umsetzung des gesetzlich vorgesehenen Widerspruchs liegt bei den Krankenhaussystemen — ohne gemeinsame Datenstruktur oder Prozesslogik. Krankenhausportale sind in diesen Prozess nicht eingebunden. FHIR Consent wäre ein geeigneter Standard, ist aber nicht durchgängig implementiert.",
    forderungen: "Einwilligungsmanagement in der ePA verankern — nicht in heterogenen Krankenhaussystemen.\nWiderspruch gegen Zugriff und Befüllung der ePA zentral und standardisiert abbilden, nicht an KIS delegieren.\nKrankenhausportale als Patientenschnittstelle einbinden — Einwilligungen und Widersprüche über das Portal erteilen und verwalten.\nConsent-Abbildung für weitere Anwendungsfälle ermöglichen (z.B. Studienteilnahme, Broad-Consent).\nUnabhängige Treuhandstellen als mögliches Modell für die Verwaltung von Consent-Informationen prüfen."
  },

  // ── Im Krankenhaus ───────────────────────────────────────────────────────────

  {
    nr: 7,
    phase: "im",
    titel: "Digitaler Check-in",
    akteur: ["Patient", "Verwaltung"],
    objekt: ["Check-in Bestätigung"],
    op: "E",
    dr: ["portal", "versorgung"],
    domäne: "Patient",
    gesetze: ["DSGVO Art. 6", "SGB V § 39", "KHZG"],
    standards: ["HL7 FHIR R4 (Encounter)", "IHE PIX/PDQ", "ISiK Basismodul"],
    struktur: "strukturiert",
    detail: "Bestätigung der Anwesenheit. Auslöser des stationären Prozesses – verbindet das Portal mit der Verwaltung.",
    ist: "",
    luecke: "",
    forderungen: ""
  },
  {
    nr: 8,
    phase: "im",
    titel: "Administrative Aufnahme",
    akteur: ["Verwaltung"],
    objekt: ["Patientenfall / Fallakte"],
    op: "E",
    dr: ["versorgung"],
    domäne: "Patient",
    gesetze: ["DSGVO Art. 9", "KHEntgG § 2", "SGB V § 39"],
    standards: ["HL7 v2", "HL7 FHIR R4 (Encounter)", "ISiK Basismodul"],
    struktur: "strukturiert",
    detail: "Fallanlage im KIS. Zentrales Datenobjekt für den gesamten stationären Aufenthalt.",
    ist: "",
    luecke: "",
    forderungen: ""
  },
  {
    nr: 9,
    phase: "im",
    titel: "Pflegeassessment",
    akteur: ["Pflege"],
    objekt: ["Pflegeassessment"],
    op: "E",
    dr: ["versorgung"],
    domäne: "Pflege",
    gesetze: ["DSGVO Art. 9", "SGB XI § 14 (Pflegebedürftigkeit)", "KrPflG"],
    standards: ["HL7 FHIR R4 (Observation)", "SNOMED CT", "LOINC", "DIN EN ISO/IEEE 11073 Point of Care"],
    struktur: "unstrukturiert",
    detail: "Erfassung des pflegerischen Bedarfs bei Aufnahme – Mobilität, Ernährung, Risikoscreening. Eigenständiges Datenobjekt der Pflege.",
    ist: "",
    luecke: "",
    forderungen: ""
  },
  {
    nr: 10,
    phase: "im",
    titel: "Durchführung diagnostischer Maßnahmen",
    akteur: ["Arzt", "Pflege"],
    objekt: ["Untersuchungsergebnisse / Befunde"],
    op: "E",
    dr: ["versorgung", "epa", "ehds"],
    domäne: "Befunde",
    gesetze: ["DSGVO Art. 9", "BGB § 630a (Behandlungsvertrag)", "MBO-Ä § 10"],
    standards: ["HL7 FHIR R4 (DiagnosticReport)", "LOINC", "DICOM", "IHE RAD", "DIN EN ISO/IEEE 11073 Point of Care"],
    struktur: "teilstrukturiert",
    detail: "Untersuchungen und Diagnostik. Erzeugt medizinische Kerndaten – sollten strukturiert vorliegen für optimale Weiterverarbeitung.",
    ist: "",
    luecke: "",
    forderungen: ""
  },
  {
    nr: 11,
    phase: "im",
    titel: "Dokumentation medizinischer Ergebnisse",
    akteur: ["Arzt"],
    objekt: ["Diagnose / Befunddokumentation"],
    op: "E, V",
    dr: ["versorgung", "epa", "ehds"],
    domäne: "Diagnosen",
    gesetze: ["DSGVO Art. 9", "BGB § 630f (Dokumentationspflicht)", "MBO-Ä § 10"],
    standards: ["HL7 FHIR R4 (Condition)", "ICD-10-GM", "OPS", "HL7 CDA R2"],
    struktur: "teilstrukturiert",
    detail: "Befunde und Diagnosen werden dokumentiert. Zentrales Datenobjekt – wird laufend verändert und ergänzt.",
    ist: "",
    luecke: "",
    forderungen: ""
  },
  {
    nr: 12,
    phase: "im",
    titel: "Pflegedokumentation",
    akteur: ["Pflege"],
    objekt: ["Pflegedokumentation / Vitalwerte"],
    op: "E, V",
    dr: ["versorgung", "epa"],
    domäne: "Pflege",
    gesetze: ["DSGVO Art. 9", "BGB § 630f (Dokumentationspflicht)", "SGB XI"],
    standards: ["HL7 FHIR R4 (Observation)", "SNOMED CT", "LOINC", "DIN EN ISO/IEEE 11073 Point of Care"],
    struktur: "teilstrukturiert",
    detail: "Laufende Dokumentation von Pflegemaßnahmen, Vitalwerten und Verlauf. Wird kontinuierlich ergänzt.",
    ist: "",
    luecke: "",
    forderungen: ""
  },
  {
    nr: 13,
    phase: "im",
    titel: "Bereitstellung Informationen im Portal",
    akteur: ["Arzt", "Verwaltung"],
    objekt: ["Laborwerte / Befunde im Portal"],
    op: "E",
    dr: ["portal", "versorgung"],
    domäne: "Befunde",
    gesetze: ["DSGVO Art. 9", "BGB § 630g (Akteneinsicht)", "KHZG", "SGB V § 341 ff. (ePA)"],
    standards: ["HL7 FHIR R4 (DocumentReference)", "gematik ePA-Spezifikation", "ISiK Basismodul"],
    struktur: "teilstrukturiert",
    detail: "Ausgewählte Informationen werden dem Patienten im Portal bereitgestellt – z.B. Laborwerte. Strukturierte Daten ermöglichen eine sinnvolle Darstellung.",
    ist: "",
    luecke: "",
    forderungen: ""
  },
  {
    nr: 14,
    phase: "im",
    titel: "Kommunikation mit Behandlungsteam",
    akteur: ["Patient", "Arzt", "Pflege"],
    objekt: ["Nachricht / Rückfrage"],
    op: "E",
    dr: ["portal", "versorgung", "epa"],
    domäne: "Kommunikation",
    gesetze: ["DSGVO Art. 9", "StGB § 203 (Schweigepflicht)", "TKG"],
    standards: ["gematik TI-Messenger", "KIM (Kommunikation im Medizinwesen)", "HL7 FHIR R4 (Communication)"],
    struktur: "unstrukturiert",
    detail: "Nachrichten und Rückfragen – unabhängig vom Übertragungsweg (Portal, TI-Messenger oder andere Kanäle).",
    ist: "",
    luecke: "",
    forderungen: ""
  },
  {
    nr: 15,
    phase: "im",
    titel: "Entlassungsvorbereitung",
    akteur: ["Arzt", "Verwaltung", "Sozialdienst"],
    objekt: ["Entlassungsplan"],
    op: "E",
    dr: ["versorgung", "epa"],
    domäne: "Nachsorge",
    gesetze: ["SGB V § 39 (Entlassmanagement)", "DSGVO Art. 9"],
    standards: ["HL7 FHIR R4 (EpisodeOfCare)", "HL7 CDA R2", "ISiK Basismodul"],
    struktur: "unstrukturiert",
    detail: "Organisation der Entlassung. Auslöser für mehrere nachgelagerte Prozesse – Pflegeüberleitung, AHB, Nachsorgetermin.",
    ist: "",
    luecke: "",
    forderungen: ""
  },
  {
    nr: 16,
    phase: "im",
    titel: "Pflegerische Entlassungsplanung",
    akteur: ["Pflege", "Sozialdienst"],
    objekt: ["Pflegerischer Überleitungsbogen"],
    op: "E",
    dr: ["versorgung", "epa"],
    domäne: "Nachsorge",
    gesetze: ["SGB V § 39 (Entlassmanagement)", "SGB XI § 37", "DSGVO Art. 9"],
    standards: ["HL7 FHIR R4 (CarePlan)", "SNOMED CT"],
    struktur: "unstrukturiert",
    detail: "Pflegerische Bedarfserfassung und Weitergabe. Eigenständiges Datenobjekt – intern für die Planung.",
    ist: "",
    luecke: "",
    forderungen: ""
  },
  {
    nr: 17,
    phase: "im",
    titel: "Pflegeüberleitung",
    akteur: ["Sozialdienst", "Pflege"],
    objekt: ["Pflegeüberleitungsdokument"],
    op: "E",
    dr: ["versorgung", "epa"],
    domäne: "Nachsorge",
    gesetze: ["SGB V § 39 (Entlassmanagement)", "SGB XI § 37", "DSGVO Art. 9"],
    standards: ["HL7 FHIR R4 (CarePlan)", "IHE XDS.b", "HL7 CDA R2"],
    struktur: "unstrukturiert",
    detail: "Bedarfserfassung und Organisation der pflegerischen Weiterversorgung. Das Überleitungsdokument geht an die nachversorgende Einrichtung.",
    ist: "",
    luecke: "",
    forderungen: ""
  },
  {
    nr: 18,
    phase: "im",
    titel: "AHB / Reha beantragen",
    akteur: ["Arzt", "Sozialdienst"],
    objekt: ["AHB / Reha-Antrag"],
    op: "E",
    dr: ["versorgung", "epa"],
    domäne: "Nachsorge",
    gesetze: ["SGB V § 40 (Anschlussheilbehandlung)", "SGB IX", "DSGVO Art. 9"],
    standards: ["HL7 FHIR R4 (ServiceRequest)", "KBV FHIR-Basisprofile"],
    struktur: "unstrukturiert",
    detail: "Antragstellung und Weiterleitung an Kostenträger. Erzeugt ein eigenständiges Datenobjekt mit Weiterleitung an externe Akteure.",
    ist: "",
    luecke: "",
    forderungen: ""
  },

  // ── Nach dem Krankenhaus ─────────────────────────────────────────────────────

  {
    nr: 19,
    phase: "nach",
    titel: "Bereitstellung Entlassdokumente",
    akteur: ["Arzt", "Verwaltung"],
    objekt: ["Arztbrief / Entlassbericht"],
    op: "E",
    dr: ["portal", "versorgung", "epa", "ehds"],
    domäne: "Dokumente",
    gesetze: ["BGB § 630f + § 630g", "DSGVO Art. 9", "SGB V § 39 (Entlassmanagement)", "MBO-Ä § 10"],
    standards: ["HL7 CDA R2", "HL7 FHIR R4 (DocumentReference)", "IHE XDS.b", "gematik ePA-Spezifikation"],
    struktur: "unstrukturiert",
    detail: "Arztbrief und Befunde nach Entlassung. Zentrales Übergabedokument – sollte strukturiert vorliegen, nicht nur als PDF.",
    ist: "",
    luecke: "",
    forderungen: ""
  },
  {
    nr: 20,
    phase: "nach",
    titel: "Bereitstellung Medikationsplan",
    akteur: ["Arzt"],
    objekt: ["Medikationsplan"],
    op: "E",
    dr: ["portal", "versorgung", "epa", "ehds"],
    domäne: "Medikation",
    gesetze: ["SGB V § 31a (Medikationsplan)", "DSGVO Art. 9", "AMVV § 14"],
    standards: ["HL7 FHIR R4 (MedicationStatement)", "KBV Medikationsplan", "ABDA Medikationsliste"],
    struktur: "teilstrukturiert",
    detail: "Aktueller Medikationsplan nach Entlassung. Klassisches Konsistenzproblem – existiert heute oft mehrfach und nicht synchronisiert.",
    ist: "",
    luecke: "",
    forderungen: ""
  },
  {
    nr: 21,
    phase: "nach",
    titel: "Bereitstellung Dokumente für ePA",
    akteur: ["Arzt", "Verwaltung"],
    objekt: ["Strukturierte Datenobjekte in der ePA"],
    op: "E",
    dr: ["epa", "ehds"],
    domäne: "Dokumente",
    gesetze: ["SGB V § 341–360 (ePA)", "DSGVO Art. 9", "PatDatSchG"],
    standards: ["HL7 FHIR R4 (DocumentReference)", "IHE MHD", "gematik ePA-Spezifikation"],
    struktur: "unstrukturiert",
    detail: "Upload strukturierter Datenobjekte in die ePA. Ziel: keine Dokumente, sondern maschinenlesbare strukturierte Daten.",
    ist: "",
    luecke: "",
    forderungen: ""
  },
  {
    nr: 22,
    phase: "nach",
    titel: "Nachsorgetermin vereinbaren",
    akteur: ["Patient", "Verwaltung"],
    objekt: ["Nachsorgetermin"],
    op: "E",
    dr: ["portal", "versorgung"],
    domäne: "Termin",
    gesetze: ["SGB V § 39 (Entlassmanagement)", "SGB V § 75a", "DSGVO Art. 6"],
    standards: ["HL7 FHIR R4 (Appointment)", "ISiK Terminplanung"],
    struktur: "strukturiert",
    detail: "Terminplanung nach Entlassung. Portal als primäre Schnittstelle für den Patienten.",
    ist: "",
    luecke: "",
    forderungen: ""
  },
  {
    nr: 23,
    phase: "nach",
    titel: "Digitale Verlaufserfassung",
    akteur: ["Patient"],
    objekt: ["Verlaufsdokumentation / PROMs"],
    op: "E",
    dr: ["portal", "versorgung", "epa"],
    domäne: "Verlauf",
    gesetze: ["DSGVO Art. 9", "SGB V § 68a (DiGA)", "DiGAV"],
    standards: ["HL7 FHIR R4 (QuestionnaireResponse)", "HL7 FHIR R4 (Observation)", "LOINC"],
    struktur: "teilstrukturiert",
    detail: "Fragebögen und PROMs nach Entlassung. Patient als aktiver Datenerzeuger – strukturierte Rückmeldungen ermöglichen Automatisierung.",
    ist: "",
    luecke: "",
    forderungen: ""
  },
  {
    nr: 24,
    phase: "nach",
    titel: "Kommunikation mit Klinik",
    akteur: ["Patient", "Arzt"],
    objekt: ["Nachricht / Rückfrage"],
    op: "E, V",
    dr: ["portal", "versorgung", "epa"],
    domäne: "Kommunikation",
    gesetze: ["DSGVO Art. 9", "StGB § 203 (Schweigepflicht)", "TKG"],
    standards: ["gematik TI-Messenger", "KIM (Kommunikation im Medizinwesen)", "HL7 FHIR R4 (Communication)"],
    struktur: "unstrukturiert",
    detail: "Rückfragen nach Entlassung – unabhängig vom Übertragungsweg.",
    ist: "",
    luecke: "",
    forderungen: ""
  },
  {
    nr: 25,
    phase: "nach",
    titel: "Abschluss der Behandlung",
    akteur: ["Arzt", "Verwaltung"],
    objekt: ["Abschlussdokumentation / Fallabschluss"],
    op: "E",
    dr: ["versorgung", "epa"],
    domäne: "Dokumente",
    gesetze: ["BGB § 630f (Dokumentationspflicht)", "DSGVO Art. 9", "KHEntgG", "SGB V § 301"],
    standards: ["HL7 FHIR R4 (EpisodeOfCare)", "IHE XDS.b", "HL7 CDA R2"],
    struktur: "strukturiert",
    detail: "Behandlungsfall wird abgeschlossen. Finales Datenobjekt des Patientenpfads.",
    ist: "",
    luecke: "",
    forderungen: ""
  }
];
